FORMAT: 1A
HOST: http://momomods.apiblueprint.org/

# MoMoMods

MoMoMods helps you plan your timetable with friends!

## Timetable [/{year}/{sem}/timetable]

### Get Timetable for year and sem [GET]

+ Response 200 (application/json)

        [
            {
                "module_code": "CS1010",
                "lesson_type": "sectional",
                "class_number": "1"
            }
        ]

### Add module to Timetable [POST]

You can add a module to a timetable.
The response is the complete timetable for year and sem with the module added.

+ Request (application/json)

        [
            {
                "module_code": "CS1010",
                "lesson_type": "tutorial",
                "class_number": "2",
            }
        ]

+ Response 201 (application/json)

        [
            {
                "module_code": "CS1010",
                "lesson_type": "sectional",
                "class_number": "1"
            },
            {
                "module_code": "CS1010",
                "lesson_type": "tutorial",
                "class_number": "2",
            }
        ]
        
## Group Collection [/{year}/{sem}/group]

### List groups I belong to [GET]

+ Response 200 (application/json)

        [
            {
                "group_id": "1",
                "group_name": "3216 assignment 3",
                "members": ["1", "2"]
            }
        ]

### Create a new group [POST]

+ Request (application/json)

        [
            {
                "group_name": "3216 final project"
            }
        ]

+ Response 200 (application/json)

        [
            {
                "group_id": "3",
                "group_name": "3216 final project",
                "members": ["1"]
            }
        ]
        
## Group [/{year}/{sem}/group/{id}]

### Get group info [GET]

+ Response 200 (application/json)

        {
            "group_id": "{id}",
            "group_name": "3216 final project",
            "members": ["1", "2"]
        }

### Add members to group [POST]

+ Request (application/json)

        {
            "members": ["2", "3"]
        }

+ Response 200 (application/json)

        [
            {
                "group_id": "3",
                "group_name": "3216 final project",
                "members": ["1", "2", "3"]
            }
        ]
        
## Friends [/friends]

### Get connected friends [GET]

+ Response 200 (application/json)

        [
            {
                "friend_name": "Niko",
                "user_id": "2"
            },
            {
                "friend_name": "Mich",
                "user_id": "3"
            },
            {
                "friend_name": "Pat",
                "user_id": "3"
            }
        ]