/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const LOG_USER_IN = 'LOG_USER_IN';
export const LOG_USER_OUT = 'LOG_USER_OUT';

export const ADD_MODULE = 'ADD_MODULE';
export const REMOVE_MODULE = 'REMOVE_MODULE';
export const CHANGE_LESSON = 'CHANGE_LESSON';
export const CHANGE_TO_LESSON = 'CHANGE_TO_LESSON';
export const CANCEL_CHANGE_LESSON = 'CANCEL_CHANGE_LESSON';
export const FETCH_TIMETABLE = 'FETCH_TIMETABLE';
export const SUBMIT_TIMETABLE = 'SUBMIT_TIMETABLE';
export const LOAD_TIMETABLE = 'LOAD_TIMETABLE';
export const SAVE_TIMETABLE = 'SAVE_TIMETABLE';

export const FETCH_MODULES = 'FETCH_MODULES';

// for testing purposes only
export const FETCH_NUS_MODS_MODULES = 'FETCH_NUS_MODS_MODULES';
export const FETCH_NUS_MODS_DETAIL = 'FETCH_NUS_MODS_DETAIL';
export const FETCH_NUS_MODS_MODULES_LIST = 'FETCH_NUS_MODS_MODULES_LIST';

export const CREATE_GROUP = 'CREATE_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const FETCH_GROUPS = 'FETCH_GROUPS';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const FETCH_GROUP_TIMETABLE = "FETCH_GROUP_TIMETABLE";

export const CHANGE_SEMESTER = 'CHANGE_SEMESTER';
export const CHANGE_YEAR = 'CHANGE_YEAR';

export const LOAD_THEME = 'LOAD_THEME';

export const FETCH_FRIENDS = 'FETCH_FRIENDS';
